[package]
name = "drogue-client"
version = "0.5.0"
authors = ["Jens Reimann <jreimann@redhat.com>"]
license = "Apache-2.0"
description = "Clients for the Drogue IoT Cloud APIs"
repository = "https://github.com/drogue-iot/drogue-client"
homepage = "https://drogue.io"
categories = ["api-bindings"]
keywords = ["IoT", "API"]
readme = "README.md"

edition = "2018"

[dependencies]
log = "0.4"
async-std = "1"
thiserror = "1"

reqwest = { version = "0.11", optional = true }
openid = "0.9"
url = "2"

chrono = "0.4"

serde = "1"
serde_json = "1"
base64-serde = "0.6"
base64 = "0.13"

[features]
default = ["reqwest"]